//! SharpFuzz harness generator for C# fuzz targets.

/// Generate a SharpFuzz harness for a C# method.
///
/// When `params` contains a type that includes "Stream", the harness passes a
/// `Stream` directly to the method; otherwise it decodes the raw bytes as a
/// UTF-8 string first.
pub fn csharp_fuzz_harness(class: &str, method: &str, params: &[&str]) -> String {
    let uses_stream = params.iter().any(|p| p.contains("Stream"));
    let mut harness = String::new();

    harness.push_str("// Auto-generated by APEX\n");
    harness.push_str("using SharpFuzz;\n");
    harness.push_str("using System;\n");
    harness.push_str("using System.IO;\n\n");
    harness.push_str("namespace ApexFuzz\n{\n");
    harness.push_str("    class Program\n    {\n");
    harness.push_str("        static void Main(string[] args)\n        {\n");

    if uses_stream {
        harness.push_str(&format!(
            "            Fuzzer.Run(stream => {{\n                {class}.{method}(stream);\n            }});\n"
        ));
    } else {
        harness.push_str(&format!(
            "            Fuzzer.Run(data => {{\n                var input = System.Text.Encoding.UTF8.GetString(data);\n                {class}.{method}(input);\n            }});\n"
        ));
    }

    harness.push_str("        }\n    }\n}\n");
    harness
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_csharp_fuzz_harness() {
        let harness = csharp_fuzz_harness("MyNamespace.Parser", "Parse", &["string input"]);
        assert!(harness.contains("using SharpFuzz"));
        assert!(harness.contains("Fuzzer.Run"));
        assert!(harness.contains("Parse"));
    }

    #[test]
    fn csharp_harness_with_stream_input() {
        let harness = csharp_fuzz_harness("MyNamespace.Parser", "Parse", &["Stream input"]);
        assert!(harness.contains("stream =>"));
        assert!(harness.contains("Fuzzer.Run"));
        assert!(harness.contains("Parse"));
    }

    #[test]
    fn csharp_harness_string_variant_uses_utf8_decode() {
        let harness = csharp_fuzz_harness("Acme.Lib", "Process", &["string data"]);
        assert!(harness.contains("UTF8.GetString"));
        assert!(!harness.contains("stream =>"));
    }

    #[test]
    fn csharp_harness_contains_namespace_and_class() {
        let harness = csharp_fuzz_harness("My.Corp.Validator", "Validate", &["string input"]);
        assert!(harness.contains("namespace ApexFuzz"));
        assert!(harness.contains("My.Corp.Validator"));
        assert!(harness.contains("Validate"));
    }

    #[test]
    fn csharp_harness_stream_variant_does_not_decode_utf8() {
        let harness = csharp_fuzz_harness("Acme.Parser", "ReadFrom", &["Stream s"]);
        assert!(!harness.contains("UTF8.GetString"));
        assert!(harness.contains("stream =>"));
    }

    #[test]
    fn csharp_harness_multiple_params_picks_stream_when_present() {
        let harness = csharp_fuzz_harness("Acme.Codec", "Decode", &["int flags", "Stream source"]);
        assert!(harness.contains("stream =>"));
    }
}
