//! libFuzzer harness generator for Swift fuzz targets.

/// Generate a libFuzzer harness for a Swift method.
///
/// Produces a Swift source file that exports `LLVMFuzzerTestOneInput` via
/// `@_cdecl`, which is the entry point recognised by the Swift/LLVM fuzzer
/// runtime when compiled with `-sanitize=fuzzer`.
pub fn swift_fuzz_harness(type_name: &str, method: &str, _params: &[&str]) -> String {
    let mut harness = String::new();

    harness.push_str("// Auto-generated by APEX\n");
    harness.push_str("import Foundation\n\n");
    harness.push_str("@_cdecl(\"LLVMFuzzerTestOneInput\")\n");
    harness.push_str("func fuzzTest(_ data: UnsafePointer<UInt8>, _ size: Int) -> Int32 {\n");
    harness.push_str("    let bytes = Data(bytes: data, count: size)\n");
    harness.push_str(&format!("    let _ = try? {type_name}.{method}(bytes)\n"));
    harness.push_str("    return 0\n");
    harness.push_str("}\n");
    harness
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_swift_fuzz_harness() {
        let harness = swift_fuzz_harness("Parser", "parse", &["Data"]);
        assert!(harness.contains("import Foundation"));
        assert!(harness.contains("parse"));
    }

    #[test]
    fn swift_harness_contains_llvm_entry_point() {
        let harness = swift_fuzz_harness("Lexer", "tokenize", &["Data"]);
        assert!(harness.contains("@_cdecl(\"LLVMFuzzerTestOneInput\")"));
        assert!(harness.contains("LLVMFuzzerTestOneInput"));
    }

    #[test]
    fn swift_harness_wraps_bytes_in_data() {
        let harness = swift_fuzz_harness("Decoder", "decode", &["Data"]);
        assert!(harness.contains("Data(bytes: data, count: size)"));
    }

    #[test]
    fn swift_harness_calls_target_method() {
        let harness = swift_fuzz_harness("JSONParser", "parseJSON", &["Data"]);
        assert!(harness.contains("JSONParser.parseJSON(bytes)"));
    }

    #[test]
    fn swift_harness_returns_zero() {
        let harness = swift_fuzz_harness("Validator", "validate", &["Data"]);
        assert!(harness.contains("return 0"));
    }

    #[test]
    fn swift_harness_uses_try_to_swallow_errors() {
        let harness = swift_fuzz_harness("XmlParser", "parse", &["Data"]);
        assert!(harness.contains("try?"));
    }
}
