//! SymCC concolic backend — compilation-based symbolic execution.
//!
//! SymCC instruments a C/C++ binary at compile-time using LLVM, producing
//! a binary that records path constraints as it executes concrete inputs.
//! This is 10-100x faster than interpreter-based concolic execution (e.g. KLEE).
//!
//! # Availability
//!
//! SymCC is an optional enhancement. When the `symcc` binary is not found on
//! PATH (or at the configured path), `is_available()` returns `false` and all
//! operations return `Err` gracefully — the orchestrator can fall back to
//! `StaticConcolicStrategy`.
//!
//! # Constraint output
//!
//! SymCC writes SMT-like constraints to `SYMCC_OUTPUT_DIR`. Each file in that
//! directory contains a concrete test case that exercises a new path branch.
//! We parse the file names and contents into `PathConstraint` structs and
//! convert them to `InputSeed`s for the fuzzing corpus.

use apex_core::{
    error::{ApexError, Result},
    traits::Strategy,
    types::{ExecutionResult, ExplorationContext, InputSeed, SeedOrigin},
};
use async_trait::async_trait;
use std::path::{Path, PathBuf};
use tracing::{debug, info, warn};

// ---------------------------------------------------------------------------
// PathConstraint — represents one concrete input generated by SymCC
// ---------------------------------------------------------------------------

/// A single concrete test case produced by SymCC when it negates a branch
/// condition along the execution path.
#[derive(Debug, Clone)]
pub struct PathConstraint {
    /// Raw bytes of the input that exercises this path.
    pub input: Vec<u8>,
    /// Human-readable label from the output file name (e.g. "000003").
    pub label: String,
}

// ---------------------------------------------------------------------------
// SymCcBackend — wraps the symcc binary
// ---------------------------------------------------------------------------

/// Low-level interface to a SymCC installation.
///
/// The backend locates the `symcc` compiler wrapper and uses it to:
/// 1. Compile a target source file into a symbolically-instrumented binary.
/// 2. Run that binary with a concrete input while capturing generated
///    constraints (= new concrete inputs) from `SYMCC_OUTPUT_DIR`.
pub struct SymCcBackend {
    /// Path to the `symcc` wrapper binary.  `None` means "search PATH".
    symcc_path: Option<PathBuf>,
}

impl Default for SymCcBackend {
    fn default() -> Self {
        Self::new()
    }
}

impl SymCcBackend {
    /// Create a backend that searches PATH for `symcc`.
    pub fn new() -> Self {
        SymCcBackend { symcc_path: None }
    }

    /// Create a backend that uses a specific `symcc` binary.
    pub fn with_path(path: impl Into<PathBuf>) -> Self {
        SymCcBackend {
            symcc_path: Some(path.into()),
        }
    }

    /// Returns `true` if the `symcc` binary is found and executable.
    pub fn is_available(&self) -> bool {
        match &self.symcc_path {
            Some(p) => p.is_file(),
            None => which_symcc().is_some(),
        }
    }

    /// Compile `target` (a C/C++ source file) with SymCC instrumentation.
    ///
    /// Returns the path of the resulting instrumented binary.
    ///
    /// # Errors
    ///
    /// Returns `Err` if SymCC is not available, compilation fails, or the
    /// output binary is not produced.
    pub fn compile(&self, target: &Path) -> Result<PathBuf> {
        let compiler = self.symcc_binary()?;
        let out = target.with_extension("symcc");

        debug!(
            compiler = %compiler.display(),
            target = %target.display(),
            output = %out.display(),
            "symcc: compiling"
        );

        let status = std::process::Command::new(&compiler)
            .args(["-O1", "-o"])
            .arg(&out)
            .arg(target)
            .status()
            .map_err(|e| ApexError::Other(format!("symcc exec error: {e}")))?;

        if !status.success() {
            return Err(ApexError::Subprocess {
                exit_code: status.code().unwrap_or(-1),
                stderr: "symcc compilation failed (rerun with RUST_LOG=debug for details)".into(),
            });
        }

        if !out.exists() {
            return Err(ApexError::Other(format!(
                "symcc produced no output binary at {}",
                out.display()
            )));
        }

        info!(binary = %out.display(), "symcc: compiled instrumented binary");
        Ok(out)
    }

    /// Execute `binary` with `input` as stdin, collect SymCC-generated
    /// concrete inputs from the output directory.
    ///
    /// Returns a list of `PathConstraint`s — one per file written by SymCC.
    ///
    /// # Errors
    ///
    /// Returns `Err` if SymCC is not available, the binary can't be run, or
    /// the output directory can't be created / read.
    pub fn run_with_input(&self, binary: &Path, input: &[u8]) -> Result<Vec<PathConstraint>> {
        if !self.is_available() {
            return Err(ApexError::Other(
                "symcc is not available on this system".into(),
            ));
        }

        // Create a temporary output directory for this run.
        let out_dir = std::env::temp_dir().join(format!(
            "apex-symcc-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .subsec_nanos()
        ));
        std::fs::create_dir_all(&out_dir)?;

        debug!(
            binary = %binary.display(),
            out_dir = %out_dir.display(),
            input_len = input.len(),
            "symcc: running instrumented binary"
        );

        // Write input to a temp file (stdin redirection).
        let input_file = out_dir.join("input.bin");
        std::fs::write(&input_file, input)?;

        let output = std::process::Command::new(binary)
            .env("SYMCC_OUTPUT_DIR", &out_dir)
            .env("SYMCC_ENABLE_LINEARIZATION", "1")
            .stdin(std::fs::File::open(&input_file)?)
            .output()
            .map_err(|e| ApexError::Other(format!("symcc run error: {e}")))?;

        if !output.status.success() {
            warn!(
                exit_code = output.status.code().unwrap_or(-1),
                "symcc: binary exited non-zero (may still have produced constraints)"
            );
        }

        let constraints = parse_output_dir(&out_dir)?;
        debug!(count = constraints.len(), "symcc: collected constraints");

        // Best-effort cleanup — ignore errors.
        let _ = std::fs::remove_dir_all(&out_dir);

        Ok(constraints)
    }

    // -- helpers --

    fn symcc_binary(&self) -> Result<PathBuf> {
        if let Some(ref p) = self.symcc_path {
            if p.is_file() {
                return Ok(p.clone());
            }
            return Err(ApexError::Other(format!(
                "configured symcc path not found: {}",
                p.display()
            )));
        }
        which_symcc().ok_or_else(|| {
            ApexError::Other(
                "symcc not found on PATH — install from https://github.com/eurecom-s3/symcc".into(),
            )
        })
    }
}

/// Search PATH for `symcc`.
fn which_symcc() -> Option<PathBuf> {
    std::env::var_os("PATH").and_then(|path_val| {
        std::env::split_paths(&path_val).find_map(|dir| {
            let candidate = dir.join("symcc");
            if candidate.is_file() {
                Some(candidate)
            } else {
                None
            }
        })
    })
}

/// Read all files in `dir` (excluding `input.bin`) as `PathConstraint`s.
fn parse_output_dir(dir: &Path) -> Result<Vec<PathConstraint>> {
    let mut constraints = Vec::new();

    let entries = std::fs::read_dir(dir)?;
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let name = path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("")
            .to_string();
        // Skip the seed input we wrote ourselves.
        if name == "input.bin" {
            continue;
        }
        match std::fs::read(&path) {
            Ok(data) if !data.is_empty() => {
                constraints.push(PathConstraint {
                    input: data,
                    label: name,
                });
            }
            Ok(_) => {
                debug!(file = %path.display(), "symcc: skipping empty output file");
            }
            Err(e) => {
                warn!(file = %path.display(), error = %e, "symcc: could not read output file");
            }
        }
    }

    // Deterministic order so callers can rely on stable iteration.
    constraints.sort_by(|a, b| a.label.cmp(&b.label));
    Ok(constraints)
}

// ---------------------------------------------------------------------------
// SymCcStrategy — wraps SymCcBackend as a Strategy
// ---------------------------------------------------------------------------

/// A [`Strategy`] that uses SymCC to generate new inputs by negating path
/// conditions encountered during concrete execution.
///
/// When SymCC is not installed, `suggest_inputs` returns an empty vector
/// rather than an error, so the orchestrator can compose it safely with
/// other strategies.
pub struct SymCcStrategy {
    backend: SymCcBackend,
    /// Pre-compiled instrumented binary.  Set by [`SymCcStrategy::with_binary`].
    instrumented_binary: Option<PathBuf>,
}

impl Default for SymCcStrategy {
    fn default() -> Self {
        Self::new()
    }
}

impl SymCcStrategy {
    /// Create a strategy backed by `symcc` found on PATH.
    pub fn new() -> Self {
        SymCcStrategy {
            backend: SymCcBackend::new(),
            instrumented_binary: None,
        }
    }

    /// Create a strategy that uses a specific pre-compiled instrumented binary
    /// (skips the compile step).
    pub fn with_binary(binary: impl Into<PathBuf>) -> Self {
        SymCcStrategy {
            backend: SymCcBackend::new(),
            instrumented_binary: Some(binary.into()),
        }
    }

    /// Return the underlying backend for direct access.
    pub fn backend(&self) -> &SymCcBackend {
        &self.backend
    }
}

#[async_trait]
impl Strategy for SymCcStrategy {
    fn name(&self) -> &str {
        "symcc"
    }

    async fn suggest_inputs(&self, ctx: &ExplorationContext) -> Result<Vec<InputSeed>> {
        if !self.backend.is_available() {
            debug!("symcc: not available, skipping");
            return Ok(vec![]);
        }

        let binary = match &self.instrumented_binary {
            Some(b) => b.clone(),
            None => {
                // Attempt to compile the target.
                match self.backend.compile(&ctx.target.root) {
                    Ok(b) => b,
                    Err(e) => {
                        warn!(error = %e, "symcc: compilation failed, returning no inputs");
                        return Ok(vec![]);
                    }
                }
            }
        };

        // Use an empty seed as the initial concrete input.
        let seed = b"";
        match self.backend.run_with_input(&binary, seed) {
            Ok(constraints) => {
                let seeds = constraints
                    .into_iter()
                    .map(|c| InputSeed::new(c.input, SeedOrigin::Concolic))
                    .collect();
                Ok(seeds)
            }
            Err(e) => {
                warn!(error = %e, "symcc: run failed, returning no inputs");
                Ok(vec![])
            }
        }
    }

    async fn observe(&self, _result: &ExecutionResult) -> Result<()> {
        // SymCC is stateless between runs — no corpus to update here.
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // -----------------------------------------------------------------------
    // SymCcBackend tests
    // -----------------------------------------------------------------------

    #[test]
    fn is_available_false_when_nonexistent_path() {
        let backend = SymCcBackend::with_path("/nonexistent/path/to/symcc");
        assert!(!backend.is_available());
    }

    #[test]
    fn is_available_false_when_searching_path_and_not_installed() {
        // Override PATH to be empty so `symcc` is definitely not found.
        // We can't modify the environment reliably in tests, but we can
        // assert on the explicit-path variant which is deterministic.
        let backend = SymCcBackend::with_path("/dev/null/no-such-binary");
        assert!(!backend.is_available());
    }

    #[test]
    fn compile_returns_err_when_not_available() {
        let backend = SymCcBackend::with_path("/nonexistent/symcc");
        let result = backend.compile(Path::new("/tmp/test.c"));
        assert!(result.is_err());
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("symcc") || msg.contains("not found"),
            "unexpected error: {msg}"
        );
    }

    #[test]
    fn run_with_input_returns_err_when_not_available() {
        let backend = SymCcBackend::with_path("/nonexistent/symcc");
        let result = backend.run_with_input(Path::new("/tmp/binary"), b"hello");
        assert!(result.is_err());
    }

    // -----------------------------------------------------------------------
    // parse_output_dir tests — test the constraint parser in isolation
    // -----------------------------------------------------------------------

    #[test]
    fn parse_output_dir_empty_dir_returns_empty() {
        let dir = tempdir_for_test("parse_empty");
        let constraints = parse_output_dir(&dir).unwrap();
        assert!(constraints.is_empty());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn parse_output_dir_skips_input_bin() {
        let dir = tempdir_for_test("parse_skip_input");
        std::fs::write(dir.join("input.bin"), b"seed data").unwrap();
        let constraints = parse_output_dir(&dir).unwrap();
        assert!(constraints.is_empty(), "input.bin should be skipped");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn parse_output_dir_reads_constraint_files() {
        let dir = tempdir_for_test("parse_reads");
        std::fs::write(dir.join("000001"), b"constraint_data_a").unwrap();
        std::fs::write(dir.join("000002"), b"constraint_data_b").unwrap();
        let constraints = parse_output_dir(&dir).unwrap();
        assert_eq!(constraints.len(), 2);
        assert_eq!(constraints[0].label, "000001");
        assert_eq!(constraints[0].input, b"constraint_data_a");
        assert_eq!(constraints[1].label, "000002");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn parse_output_dir_skips_empty_files() {
        let dir = tempdir_for_test("parse_skips_empty");
        std::fs::write(dir.join("000001"), b"").unwrap(); // empty
        std::fs::write(dir.join("000002"), b"data").unwrap();
        let constraints = parse_output_dir(&dir).unwrap();
        assert_eq!(constraints.len(), 1);
        assert_eq!(constraints[0].label, "000002");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn parse_output_dir_sorted_by_label() {
        let dir = tempdir_for_test("parse_sorted");
        std::fs::write(dir.join("000003"), b"c").unwrap();
        std::fs::write(dir.join("000001"), b"a").unwrap();
        std::fs::write(dir.join("000002"), b"b").unwrap();
        let constraints = parse_output_dir(&dir).unwrap();
        assert_eq!(constraints.len(), 3);
        assert_eq!(constraints[0].label, "000001");
        assert_eq!(constraints[1].label, "000002");
        assert_eq!(constraints[2].label, "000003");
        let _ = std::fs::remove_dir_all(&dir);
    }

    // -----------------------------------------------------------------------
    // PathConstraint struct tests
    // -----------------------------------------------------------------------

    #[test]
    fn path_constraint_clone() {
        let c = PathConstraint {
            input: b"hello".to_vec(),
            label: "000001".to_string(),
        };
        let cloned = c.clone();
        assert_eq!(cloned.input, c.input);
        assert_eq!(cloned.label, c.label);
    }

    #[test]
    fn path_constraint_debug() {
        let c = PathConstraint {
            input: b"test".to_vec(),
            label: "lbl".to_string(),
        };
        let debug = format!("{c:?}");
        assert!(debug.contains("PathConstraint"));
    }

    // -----------------------------------------------------------------------
    // SymCcStrategy tests
    // -----------------------------------------------------------------------

    #[tokio::test]
    async fn strategy_name_is_symcc() {
        let s = SymCcStrategy::new();
        assert_eq!(s.name(), "symcc");
    }

    #[tokio::test]
    async fn suggest_inputs_empty_when_not_available() {
        // Point to a non-existent binary so is_available() returns false.
        let s = SymCcStrategy {
            backend: SymCcBackend::with_path("/nonexistent/symcc"),
            instrumented_binary: None,
        };
        let ctx = make_ctx();
        let inputs = s.suggest_inputs(&ctx).await.unwrap();
        assert!(inputs.is_empty(), "should return empty when symcc missing");
    }

    #[tokio::test]
    async fn observe_always_ok() {
        let s = SymCcStrategy::new();
        let result = ExecutionResult {
            seed_id: apex_core::types::SeedId::new(),
            status: apex_core::types::ExecutionStatus::Pass,
            new_branches: vec![],
            trace: None,
            duration_ms: 1,
            stdout: String::new(),
            stderr: String::new(),
            input: None,
            resource_metrics: None,
        };
        assert!(s.observe(&result).await.is_ok());
    }

    #[test]
    fn backend_accessor_works() {
        let s = SymCcStrategy::new();
        // is_available may be true or false depending on the environment;
        // we just verify the accessor doesn't panic.
        let _ = s.backend().is_available();
    }

    #[test]
    fn with_binary_stores_path() {
        let s = SymCcStrategy::with_binary("/tmp/my-instrumented-binary");
        assert_eq!(
            s.instrumented_binary.as_deref(),
            Some(Path::new("/tmp/my-instrumented-binary"))
        );
    }

    // -----------------------------------------------------------------------
    // Helper
    // -----------------------------------------------------------------------

    fn tempdir_for_test(suffix: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("apex-symcc-test-{suffix}"));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn make_ctx() -> ExplorationContext {
        ExplorationContext {
            target: apex_core::types::Target {
                root: std::path::PathBuf::from("/tmp"),
                language: apex_core::types::Language::C,
                test_command: vec![],
            },
            uncovered_branches: vec![],
            iteration: 0,
        }
    }
}
