use apex_core::{
    error::{ApexError, Result},
    traits::TestSynthesizer,
    types::{Language, SynthesizedTest, TestCandidate},
};
use std::{collections::HashSet, path::PathBuf};
use tracing::info;

pub struct JestSynthesizer {
    output_dir: PathBuf,
}

impl JestSynthesizer {
    pub fn new(output_dir: impl Into<PathBuf>) -> Self {
        JestSynthesizer {
            output_dir: output_dir.into(),
        }
    }

    fn generate_content(candidates: &[&TestCandidate]) -> String {
        let mut content = String::new();

        content.push_str("// Auto-generated by APEX — do not edit by hand.\n");
        content.push_str("// Each test targets specific uncovered branches.\n\n");
        content.push_str("'use strict';\n\n");

        for (i, candidate) in candidates.iter().enumerate() {
            if !candidate.code.trim().is_empty() {
                content.push_str(&format!("// Candidate {}\n", i + 1));
                if !candidate.reasoning.trim().is_empty() {
                    content.push_str(&format!("// {}\n", candidate.reasoning));
                }
                content.push_str(&candidate.code);
                content.push_str("\n\n");
            }
        }

        content
    }
}

impl TestSynthesizer for JestSynthesizer {
    fn language(&self) -> Language {
        Language::JavaScript
    }

    fn synthesize(&self, candidates: &[TestCandidate]) -> Result<Vec<SynthesizedTest>> {
        if candidates.is_empty() {
            return Ok(Vec::new());
        }

        // Deduplicate by code.
        let mut seen: HashSet<String> = HashSet::new();
        let mut unique: Vec<&TestCandidate> = Vec::new();
        for c in candidates {
            if c.code.trim().is_empty() {
                continue;
            }
            if seen.insert(c.code.clone()) {
                unique.push(c);
            }
        }

        if unique.is_empty() {
            return Ok(Vec::new());
        }

        let content = Self::generate_content(&unique);

        std::fs::create_dir_all(&self.output_dir)
            .map_err(|e| ApexError::Synthesis(format!("create output dir: {e}")))?;

        let file_path = self.output_dir.join("apex_generated.test.js");

        std::fs::write(&file_path, &content)
            .map_err(|e| ApexError::Synthesis(format!("write apex_generated.test.js: {e}")))?;

        info!(file = %file_path.display(), candidates = unique.len(), "wrote Jest test file");

        let covers_branches: Vec<_> = unique
            .iter()
            .flat_map(|c| c.target_branches.clone())
            .collect();

        Ok(vec![SynthesizedTest {
            path: file_path,
            content,
            covers_branches,
        }])
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use apex_core::types::BranchId;

    fn make_candidate(code: &str, branches: Vec<BranchId>) -> TestCandidate {
        let mut tc = TestCandidate::new(code.to_string(), Language::JavaScript);
        tc.target_branches = branches;
        tc
    }

    fn make_candidate_with_reasoning(code: &str, reasoning: &str) -> TestCandidate {
        let mut tc = TestCandidate::new(code.to_string(), Language::JavaScript);
        tc.reasoning = reasoning.to_string();
        tc
    }

    #[test]
    fn empty_candidates_returns_empty() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JestSynthesizer::new(dir.path());
        let result = synth.synthesize(&[]).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn single_candidate_produces_file() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JestSynthesizer::new(dir.path());
        let candidate = make_candidate(
            "describe('add', () => {\n  test('adds 1+1', () => {\n    expect(1+1).toBe(2);\n  });\n});",
            vec![BranchId::new(1, 5, 0, 0)],
        );
        let results = synth.synthesize(&[candidate]).unwrap();
        assert_eq!(results.len(), 1);

        let out = &results[0];
        assert!(out.path.exists());
        assert!(out.path.file_name().unwrap() == "apex_generated.test.js");
        assert!(out.content.contains("Auto-generated by APEX"));
        assert!(out.content.contains("'use strict'"));
        assert!(out.content.contains("expect(1+1).toBe(2)"));
        assert_eq!(out.covers_branches.len(), 1);
    }

    #[test]
    fn all_empty_code_candidates_returns_empty() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JestSynthesizer::new(dir.path());
        let c1 = make_candidate("   ", vec![]);
        let c2 = make_candidate("", vec![]);
        let results = synth.synthesize(&[c1, c2]).unwrap();
        assert!(results.is_empty());
    }

    #[test]
    fn deduplicates_identical_code() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JestSynthesizer::new(dir.path());
        let c1 = make_candidate("test('a', () => {});", vec![BranchId::new(1, 1, 0, 0)]);
        let c2 = make_candidate("test('a', () => {});", vec![BranchId::new(1, 2, 0, 0)]);
        let results = synth.synthesize(&[c1, c2]).unwrap();
        assert_eq!(results.len(), 1);

        let count = results[0].content.matches("test('a'").count();
        assert_eq!(count, 1, "duplicate code should be deduplicated");
    }

    #[test]
    fn reasoning_included_as_comment() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JestSynthesizer::new(dir.path());
        let candidate = make_candidate_with_reasoning(
            "test('edge', () => {});",
            "Tests the edge case for null input",
        );
        let results = synth.synthesize(&[candidate]).unwrap();
        assert!(results[0]
            .content
            .contains("Tests the edge case for null input"));
    }

    #[test]
    fn empty_reasoning_not_included() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JestSynthesizer::new(dir.path());
        let candidate = make_candidate("test('x', () => {});", vec![]);
        let results = synth.synthesize(&[candidate]).unwrap();
        // Should only have "// Candidate 1" but not a separate reasoning line.
        let lines: Vec<&str> = results[0]
            .content
            .lines()
            .filter(|l| {
                l.starts_with("// ") && !l.contains("Auto-generated") && !l.contains("Each test")
            })
            .collect();
        assert_eq!(lines.len(), 1); // Only "// Candidate 1"
    }

    #[test]
    fn language_is_javascript() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JestSynthesizer::new(dir.path());
        assert_eq!(synth.language(), Language::JavaScript);
    }

    #[test]
    fn branches_collected_from_multiple_candidates() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JestSynthesizer::new(dir.path());
        let c1 = make_candidate("test('a', () => {});", vec![BranchId::new(1, 10, 0, 0)]);
        let c2 = make_candidate("test('b', () => {});", vec![BranchId::new(2, 20, 0, 1)]);
        let results = synth.synthesize(&[c1, c2]).unwrap();
        assert_eq!(results[0].covers_branches.len(), 2);
    }

    // -----------------------------------------------------------------------
    // Additional coverage tests
    // -----------------------------------------------------------------------

    #[test]
    fn mixed_empty_and_non_empty_candidates() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JestSynthesizer::new(dir.path());
        let c1 = make_candidate("", vec![]);
        let c2 = make_candidate("test('real', () => { expect(1).toBe(1); });", vec![BranchId::new(1, 1, 0, 0)]);
        let c3 = make_candidate("   ", vec![]);
        let results = synth.synthesize(&[c1, c2, c3]).unwrap();
        // Only c2 has non-empty code
        assert_eq!(results.len(), 1);
        assert!(results[0].content.contains("test('real'"));
        assert_eq!(results[0].covers_branches.len(), 1);
    }

    #[test]
    fn generate_content_includes_use_strict() {
        let c = make_candidate("test('x', () => {});", vec![]);
        let content = JestSynthesizer::generate_content(&[&c]);
        assert!(content.contains("'use strict'"));
    }

    #[test]
    fn generate_content_empty_code_skipped() {
        let c1 = TestCandidate::new("".to_string(), Language::JavaScript);
        let c2_code = "test('y', () => {});";
        let c2 = make_candidate(c2_code, vec![]);
        let content = JestSynthesizer::generate_content(&[&c1, &c2]);
        // Empty code candidate should not appear
        assert!(!content.contains("// Candidate 1\n// Candidate 2"));
        assert!(content.contains("// Candidate 2"));
    }

    #[test]
    fn reasoning_with_whitespace_only_not_included() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JestSynthesizer::new(dir.path());
        let mut c = TestCandidate::new("test('z', () => {});".to_string(), Language::JavaScript);
        c.reasoning = "   ".to_string();
        let results = synth.synthesize(&[c]).unwrap();
        // Only "// Candidate 1" comment, no reasoning line
        let comment_lines: Vec<&str> = results[0]
            .content
            .lines()
            .filter(|l| {
                l.starts_with("// ") && !l.contains("Auto-generated") && !l.contains("Each test")
            })
            .collect();
        assert_eq!(comment_lines.len(), 1);
    }

    #[test]
    fn output_file_is_named_correctly() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JestSynthesizer::new(dir.path());
        let c = make_candidate("test('n', () => {});", vec![]);
        let results = synth.synthesize(&[c]).unwrap();
        assert_eq!(
            results[0].path.file_name().unwrap().to_str().unwrap(),
            "apex_generated.test.js"
        );
    }

    #[test]
    fn multiple_unique_candidates_all_included() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JestSynthesizer::new(dir.path());
        let c1 = make_candidate("test('a', () => {});", vec![]);
        let c2 = make_candidate("test('b', () => {});", vec![]);
        let c3 = make_candidate("test('c', () => {});", vec![]);
        let results = synth.synthesize(&[c1, c2, c3]).unwrap();
        assert_eq!(results.len(), 1);
        assert!(results[0].content.contains("// Candidate 1"));
        assert!(results[0].content.contains("// Candidate 2"));
        assert!(results[0].content.contains("// Candidate 3"));
    }

    #[test]
    fn deduplication_of_empty_trimmed_code() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JestSynthesizer::new(dir.path());
        let c1 = make_candidate("   ", vec![]);
        let c2 = make_candidate("  ", vec![]);
        let c3 = make_candidate("test('only', () => {});", vec![]);
        let results = synth.synthesize(&[c1, c2, c3]).unwrap();
        assert_eq!(results.len(), 1);
        let count = results[0].content.matches("// Candidate").count();
        assert_eq!(count, 1); // Only the non-empty candidate
    }
}
