use apex_core::{
    error::{ApexError, Result},
    traits::TestSynthesizer,
    types::{Language, SynthesizedTest, TestCandidate},
};
use std::{collections::HashSet, path::PathBuf};
use tracing::info;

pub struct JUnitSynthesizer {
    output_dir: PathBuf,
}

impl JUnitSynthesizer {
    pub fn new(output_dir: impl Into<PathBuf>) -> Self {
        JUnitSynthesizer {
            output_dir: output_dir.into(),
        }
    }

    fn generate_content(candidates: &[&TestCandidate]) -> String {
        let mut content = String::new();

        content.push_str("// Auto-generated by APEX \u{2014} do not edit by hand.\n");
        content.push_str("package apex.generated;\n\n");
        content.push_str("import org.junit.jupiter.api.Test;\n");
        content.push_str("import static org.junit.jupiter.api.Assertions.*;\n\n");
        content.push_str("public class ApexGeneratedTest {\n");

        for (i, candidate) in candidates.iter().enumerate() {
            if candidate.code.trim().is_empty() {
                continue;
            }

            content.push_str(&format!("    // Candidate {}\n", i + 1));

            // If the candidate code already contains the method signature, embed it as-is
            // (indented); otherwise wrap it in a generated method body.
            let code = candidate.code.trim();
            let has_signature = code.contains("void test") || code.contains("public void");

            if has_signature {
                // Indent each line of the existing method by 4 spaces.
                for line in code.lines() {
                    content.push_str("    ");
                    content.push_str(line);
                    content.push('\n');
                }
            } else {
                let method_name = format!("testApexGenerated_{i}");
                content.push_str("    @Test\n");
                content.push_str(&format!(
                    "    public void {method_name}() throws Exception {{\n"
                ));
                for line in code.lines() {
                    content.push_str("        ");
                    content.push_str(line);
                    content.push('\n');
                }
                content.push_str("    }\n");
            }

            content.push('\n');
        }

        content.push_str("}\n");
        content
    }
}

impl TestSynthesizer for JUnitSynthesizer {
    fn language(&self) -> Language {
        Language::Java
    }

    fn synthesize(&self, candidates: &[TestCandidate]) -> Result<Vec<SynthesizedTest>> {
        if candidates.is_empty() {
            return Ok(Vec::new());
        }

        // Deduplicate by code hash.
        let mut seen_hashes: HashSet<u64> = HashSet::new();
        let mut unique: Vec<&TestCandidate> = Vec::new();
        for c in candidates {
            use std::hash::{Hash, Hasher};
            let mut hasher = std::collections::hash_map::DefaultHasher::new();
            c.code.hash(&mut hasher);
            let h = hasher.finish();
            if seen_hashes.insert(h) {
                unique.push(c);
            }
        }

        let content = Self::generate_content(&unique);

        let file_path = self.output_dir.join("ApexGeneratedTest.java");

        std::fs::create_dir_all(&self.output_dir)
            .map_err(|e| ApexError::Synthesis(format!("create output dir: {e}")))?;

        std::fs::write(&file_path, &content)
            .map_err(|e| ApexError::Synthesis(format!("write ApexGeneratedTest.java: {e}")))?;

        let covers: Vec<_> = unique
            .iter()
            .flat_map(|c| c.target_branches.clone())
            .collect();

        info!(
            file = %file_path.display(),
            candidates = unique.len(),
            "wrote JUnit test file"
        );

        Ok(vec![SynthesizedTest {
            path: file_path,
            content,
            covers_branches: covers,
        }])
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use apex_core::types::BranchId;

    fn make_candidate(code: &str, branches: Vec<BranchId>) -> TestCandidate {
        let mut tc = TestCandidate::new(code.to_string(), Language::Java);
        tc.target_branches = branches;
        tc
    }

    #[test]
    fn empty_candidates_returns_empty() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JUnitSynthesizer::new(dir.path());
        let result = synth.synthesize(&[]).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn single_candidate_wraps_in_method() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JUnitSynthesizer::new(dir.path());
        let candidate = make_candidate(
            "int x = 1;\nassertEquals(1, x);",
            vec![BranchId::new(1, 10, 0, 0)],
        );
        let results = synth.synthesize(&[candidate]).unwrap();
        assert_eq!(results.len(), 1);

        let out = &results[0];
        assert!(out.path.exists());
        assert!(out.path.file_name().unwrap() == "ApexGeneratedTest.java");
        assert!(out.content.contains("Auto-generated by APEX"));
        assert!(out.content.contains("package apex.generated;"));
        assert!(out.content.contains("import org.junit.jupiter.api.Test;"));
        assert!(out
            .content
            .contains("import static org.junit.jupiter.api.Assertions.*;"));
        assert!(out.content.contains("@Test"));
        assert!(out.content.contains("public void testApexGenerated_0()"));
        assert!(out.content.contains("assertEquals(1, x)"));
        assert_eq!(out.covers_branches.len(), 1);
    }

    #[test]
    fn candidate_with_method_signature_not_double_wrapped() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JUnitSynthesizer::new(dir.path());
        let candidate = make_candidate(
            "@Test\npublic void testCustom() {\n    assertTrue(true);\n}",
            vec![],
        );
        let results = synth.synthesize(&[candidate]).unwrap();
        let content = &results[0].content;
        // Should NOT contain testApexGenerated_ since it has its own signature.
        assert!(!content.contains("testApexGenerated_"));
        assert!(content.contains("public void testCustom()"));
        assert!(content.contains("assertTrue(true)"));
    }

    #[test]
    fn deduplicates_identical_code() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JUnitSynthesizer::new(dir.path());
        let c1 = make_candidate("assertTrue(true);", vec![BranchId::new(1, 5, 0, 0)]);
        let c2 = make_candidate("assertTrue(true);", vec![BranchId::new(1, 6, 0, 0)]);
        let results = synth.synthesize(&[c1, c2]).unwrap();

        let count = results[0].content.matches("assertTrue(true)").count();
        assert_eq!(count, 1, "duplicate code should be deduplicated");
    }

    #[test]
    fn empty_code_candidate_skipped_in_output() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JUnitSynthesizer::new(dir.path());
        let c1 = make_candidate("   ", vec![]);
        let c2 = make_candidate("assertNotNull(new Object());", vec![]);
        let results = synth.synthesize(&[c1, c2]).unwrap();
        let content = &results[0].content;
        // The empty candidate should not produce a @Test method.
        assert!(content.contains("assertNotNull"));
        // Only one @Test annotation for the non-empty candidate.
        let test_count = content.matches("@Test").count();
        assert_eq!(test_count, 1);
    }

    #[test]
    fn language_is_java() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JUnitSynthesizer::new(dir.path());
        assert_eq!(synth.language(), Language::Java);
    }

    #[test]
    fn branches_collected_from_multiple_candidates() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JUnitSynthesizer::new(dir.path());
        let c1 = make_candidate("assertEquals(1, 1);", vec![BranchId::new(1, 10, 0, 0)]);
        let c2 = make_candidate("assertEquals(2, 2);", vec![BranchId::new(2, 20, 0, 1)]);
        let results = synth.synthesize(&[c1, c2]).unwrap();
        assert_eq!(results[0].covers_branches.len(), 2);
    }

    #[test]
    fn class_wrapper_present() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JUnitSynthesizer::new(dir.path());
        let candidate = make_candidate("assertEquals(1, 1);", vec![]);
        let results = synth.synthesize(&[candidate]).unwrap();
        assert!(results[0]
            .content
            .contains("public class ApexGeneratedTest {"));
        assert!(results[0].content.ends_with("}\n"));
    }

    // -----------------------------------------------------------------------
    // Additional coverage tests
    // -----------------------------------------------------------------------

    #[test]
    fn candidate_with_void_test_method_not_wrapped() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JUnitSynthesizer::new(dir.path());
        let candidate = make_candidate(
            "@Test\nvoid testSimple() {\n    assertTrue(true);\n}",
            vec![],
        );
        let results = synth.synthesize(&[candidate]).unwrap();
        let content = &results[0].content;
        // Should NOT double-wrap with testApexGenerated_
        assert!(!content.contains("testApexGenerated_"));
        assert!(content.contains("void testSimple()"));
    }

    #[test]
    fn mixed_signature_and_raw_code_candidates() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JUnitSynthesizer::new(dir.path());
        let c1 = make_candidate(
            "@Test\npublic void testExisting() {\n    assertEquals(1, 1);\n}",
            vec![BranchId::new(1, 1, 0, 0)],
        );
        let c2 = make_candidate(
            "int x = 42;\nassertEquals(42, x);",
            vec![BranchId::new(2, 2, 0, 0)],
        );
        let results = synth.synthesize(&[c1, c2]).unwrap();
        let content = &results[0].content;
        // c1 should be embedded directly (has "public void")
        assert!(content.contains("public void testExisting()"));
        // c2 should be wrapped (no method signature)
        assert!(content.contains("testApexGenerated_1"));
        assert!(content.contains("int x = 42;"));
    }

    #[test]
    fn all_empty_code_candidates_still_produce_class() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JUnitSynthesizer::new(dir.path());
        let c1 = make_candidate("   ", vec![]);
        let c2 = make_candidate("  ", vec![]);
        let results = synth.synthesize(&[c1, c2]).unwrap();
        let content = &results[0].content;
        // Class wrapper should still be present, just no @Test methods
        assert!(content.contains("public class ApexGeneratedTest {"));
        assert!(!content.contains("@Test"));
    }

    #[test]
    fn generate_content_method_numbering() {
        let c1 = make_candidate("x();", vec![]);
        let c2 = make_candidate("y();", vec![]);
        let c3 = make_candidate("z();", vec![]);
        let content = JUnitSynthesizer::generate_content(&[&c1, &c2, &c3]);
        assert!(content.contains("testApexGenerated_0"));
        assert!(content.contains("testApexGenerated_1"));
        assert!(content.contains("testApexGenerated_2"));
    }

    #[test]
    fn generate_content_indentation_of_wrapped_code() {
        let c = make_candidate("int a = 1;\nint b = 2;\nassertEquals(3, a + b);", vec![]);
        let content = JUnitSynthesizer::generate_content(&[&c]);
        // Code lines should be indented by 8 spaces (inside method body)
        assert!(content.contains("        int a = 1;"));
        assert!(content.contains("        int b = 2;"));
        assert!(content.contains("        assertEquals(3, a + b);"));
    }

    #[test]
    fn generate_content_indentation_of_existing_method() {
        let c = make_candidate(
            "@Test\npublic void testStuff() {\n    assertTrue(true);\n}",
            vec![],
        );
        let content = JUnitSynthesizer::generate_content(&[&c]);
        // Lines should be indented by 4 spaces (class level)
        assert!(content.contains("    @Test"));
        assert!(content.contains("    public void testStuff() {"));
    }

    #[test]
    fn file_path_is_correct() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JUnitSynthesizer::new(dir.path());
        let c = make_candidate("assertTrue(true);", vec![]);
        let results = synth.synthesize(&[c]).unwrap();
        assert_eq!(
            results[0].path.file_name().unwrap().to_str().unwrap(),
            "ApexGeneratedTest.java"
        );
        assert_eq!(results[0].path.parent().unwrap(), dir.path());
    }

    #[test]
    fn deduplication_with_three_same_candidates() {
        let dir = tempfile::tempdir().unwrap();
        let synth = JUnitSynthesizer::new(dir.path());
        let c1 = make_candidate("assertEquals(1, 1);", vec![BranchId::new(1, 1, 0, 0)]);
        let c2 = make_candidate("assertEquals(1, 1);", vec![BranchId::new(2, 2, 0, 0)]);
        let c3 = make_candidate("assertEquals(1, 1);", vec![BranchId::new(3, 3, 0, 0)]);
        let results = synth.synthesize(&[c1, c2, c3]).unwrap();
        // All three have same code, so only 1 unique candidate
        let count = results[0].content.matches("assertEquals(1, 1)").count();
        assert_eq!(count, 1);
        // But covers_branches should have the first occurrence's branch
        assert_eq!(results[0].covers_branches.len(), 1);
    }

    #[test]
    fn imports_always_present() {
        let c = make_candidate("assertTrue(true);", vec![]);
        let content = JUnitSynthesizer::generate_content(&[&c]);
        assert!(content.contains("import org.junit.jupiter.api.Test;"));
        assert!(content.contains("import static org.junit.jupiter.api.Assertions.*;"));
        assert!(content.contains("package apex.generated;"));
    }

    #[test]
    fn throws_exception_in_generated_method() {
        let c = make_candidate("doRisky();", vec![]);
        let content = JUnitSynthesizer::generate_content(&[&c]);
        assert!(content.contains("throws Exception"));
    }
}
