use apex_core::{
    error::{ApexError, Result},
    traits::TestSynthesizer,
    types::{Language, SynthesizedTest, TestCandidate},
};
use std::{collections::HashSet, path::PathBuf};
use tracing::info;

pub struct RubyTestSynthesizer {
    output_dir: PathBuf,
}

impl RubyTestSynthesizer {
    pub fn new(output_dir: impl Into<PathBuf>) -> Self {
        Self {
            output_dir: output_dir.into(),
        }
    }

    fn generate_file_content(candidates: &[&TestCandidate]) -> String {
        let mut content = String::new();
        content.push_str("# Auto-generated by APEX — do not edit by hand.\n");
        content.push_str("require 'rspec'\n\n");

        for (i, candidate) in candidates.iter().enumerate() {
            if !candidate.code.trim().is_empty() {
                content.push_str(&format!(
                    "# Candidate {} — targets: {}\n",
                    i + 1,
                    candidate
                        .target_branches
                        .iter()
                        .map(|b| format!("{}:{}", b.file_id, b.line))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
                content.push_str(&candidate.code);
                content.push_str("\n\n");
            }
        }

        content
    }
}

impl TestSynthesizer for RubyTestSynthesizer {
    fn language(&self) -> Language {
        Language::Ruby
    }

    fn synthesize(&self, candidates: &[TestCandidate]) -> Result<Vec<SynthesizedTest>> {
        if candidates.is_empty() {
            return Ok(Vec::new());
        }

        let mut seen_hashes: HashSet<u64> = HashSet::new();
        let mut unique: Vec<&TestCandidate> = Vec::new();
        for c in candidates {
            use std::hash::{Hash, Hasher};
            let mut hasher = std::collections::hash_map::DefaultHasher::new();
            c.code.hash(&mut hasher);
            let h = hasher.finish();
            if seen_hashes.insert(h) {
                unique.push(c);
            }
        }

        let chunk_size = 20;
        let mut outputs = Vec::new();

        for chunk in unique.chunks(chunk_size) {
            let content = Self::generate_file_content(chunk);
            let hash: u64 = {
                use std::hash::{Hash, Hasher};
                let mut h = std::collections::hash_map::DefaultHasher::new();
                content.hash(&mut h);
                h.finish()
            };
            let file_name = format!("apex_generated_{hash:016x}_spec.rb");
            let file_path = self.output_dir.join("apex_generated").join(&file_name);

            let parent = file_path
                .parent()
                .ok_or_else(|| ApexError::Synthesis("file path has no parent dir".into()))?;
            std::fs::create_dir_all(parent)
                .map_err(|e| ApexError::Synthesis(format!("create dir: {e}")))?;

            std::fs::write(&file_path, &content)
                .map_err(|e| ApexError::Synthesis(format!("write {file_name}: {e}")))?;

            let covers: Vec<_> = chunk
                .iter()
                .flat_map(|c| c.target_branches.clone())
                .collect();

            info!(file = %file_path.display(), candidates = chunk.len(), "wrote Ruby test file");

            outputs.push(SynthesizedTest {
                path: file_path,
                content,
                covers_branches: covers,
            });
        }

        Ok(outputs)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use apex_core::types::BranchId;

    fn make_candidate(code: &str, branches: Vec<BranchId>) -> TestCandidate {
        let mut tc = TestCandidate::new(code.to_string(), Language::Ruby);
        tc.target_branches = branches;
        tc
    }

    #[test]
    fn empty_candidates_returns_empty() {
        let dir = tempfile::tempdir().unwrap();
        let synth = RubyTestSynthesizer::new(dir.path());
        let result = synth.synthesize(&[]).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn single_candidate_produces_spec_rb_file() {
        let dir = tempfile::tempdir().unwrap();
        let synth = RubyTestSynthesizer::new(dir.path());
        let candidate = make_candidate(
            "RSpec.describe 'add' do\n  it 'returns 4 for 2+2' do\n    expect(2 + 2).to eq(4)\n  end\nend",
            vec![BranchId::new(1, 10, 0, 0)],
        );
        let results = synth.synthesize(&[candidate]).unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].path.extension().unwrap(), "rb");
        let name = results[0].path.file_name().unwrap().to_string_lossy();
        assert!(name.ends_with("_spec.rb"));
        assert!(results[0].content.contains("require 'rspec'"));
        assert!(results[0].content.contains("RSpec.describe"));
    }

    #[test]
    fn language_is_ruby() {
        let dir = tempfile::tempdir().unwrap();
        let synth = RubyTestSynthesizer::new(dir.path());
        assert_eq!(synth.language(), Language::Ruby);
    }

    #[test]
    fn deduplicates_identical_code() {
        let dir = tempfile::tempdir().unwrap();
        let synth = RubyTestSynthesizer::new(dir.path());
        let c1 = make_candidate(
            "RSpec.describe 'x' do\n  it 'works' do\n    expect(1).to eq(1)\n  end\nend",
            vec![BranchId::new(1, 1, 0, 0)],
        );
        let c2 = make_candidate(
            "RSpec.describe 'x' do\n  it 'works' do\n    expect(1).to eq(1)\n  end\nend",
            vec![BranchId::new(1, 2, 0, 0)],
        );
        let results = synth.synthesize(&[c1, c2]).unwrap();
        let count = results[0].content.matches("RSpec.describe 'x'").count();
        assert_eq!(count, 1);
    }

    #[test]
    fn output_in_apex_generated_subdir() {
        let dir = tempfile::tempdir().unwrap();
        let synth = RubyTestSynthesizer::new(dir.path());
        let c = make_candidate("RSpec.describe 't' do\nend", vec![]);
        let results = synth.synthesize(&[c]).unwrap();
        assert!(results[0]
            .path
            .parent()
            .unwrap()
            .ends_with("apex_generated"));
    }

    #[test]
    fn branch_targets_in_comment() {
        let dir = tempfile::tempdir().unwrap();
        let synth = RubyTestSynthesizer::new(dir.path());
        let c = make_candidate(
            "RSpec.describe 'b' do\nend",
            vec![BranchId::new(42, 7, 0, 0), BranchId::new(42, 8, 0, 1)],
        );
        let results = synth.synthesize(&[c]).unwrap();
        assert!(results[0].content.contains("42:7"));
        assert!(results[0].content.contains("42:8"));
    }

    #[test]
    fn large_batch_produces_multiple_files() {
        let dir = tempfile::tempdir().unwrap();
        let synth = RubyTestSynthesizer::new(dir.path());
        let candidates: Vec<TestCandidate> = (0..25)
            .map(|i| {
                make_candidate(
                    &format!(
                        "RSpec.describe 'item_{i}' do\n  it 'works' do\n    expect({i}).to eq({i})\n  end\nend"
                    ),
                    vec![],
                )
            })
            .collect();
        let results = synth.synthesize(&candidates).unwrap();
        assert_eq!(results.len(), 2);
    }
}
